### ISSUE TITLE
[Task] 03/22 클라이언트

### ISSUE THREAD

**Issue by mh11kim** [codestates/torys-journey#14]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: 메인페이지와 모달창 민들기

## TODO
1. [x] 메인페이지 코드 작성하기
2. [ ] 모달창 코드 작성하기
3. [ ] 메인페이지&모달창 css만들기

## Estimated time
> Pick one

`1d`

## Labels
* Estimated time: `E: 1d`
* Group : `client`
* Sprint: `Sprint__NUMBER__2`
* Urgency: `Middle`
