### ISSUE TITLE
[Task] 3/23 클라이언트-1

### ISSUE THREAD

**Issue by mh11kim** [codestates/torys-journey#16]
## ISSUE
- Group: `client`
- Type:  `feature`
- Detail:

## TODO
1. [x] 요구사항에 기능 중심으로 작성
2. [x] 플로우차트 수정
3. [x] 리액트 리덕스 등 주요 스택 버전 기재
4. [x] 와이어프레임 링크
5. [x] 베어 미니멈이 많다면 생각해보고 어드밴스드로 뺄 수 있는 것 빼기

## Estimated time
> Pick one

`3h`

## Labels
* Estimated time: `E: 3h`
* Group : `client`
* Sprint: `Sprint__NUMBER__2`
* Urgency: `Low`
