### ISSUE TITLE
[Task] 3/28 김동길

### ISSUE THREAD

**Issue by GilDDo** [codestates/torys-journey#20]
## ISSUE
- Group: `server`
- Type:  `feature`
- Detail:

## TODO
1. [x] 회원가입 기능 구현
2. [x] 로그인 기능 구현
3. [x] 로그아웃 기능 구현

## Estimated time
> `3h`

## Labels
* Estimated time: `E: 3h`
* Group : `server`
* Sprint: `Sprint__NUMBER__2`
* Urgency: `High`
