### ISSUE TITLE
[Task] 3/25 클라이언트

### ISSUE THREAD

**Issue by mh11kim** [codestates/torys-journey#21]
## ISSUE
- Group: `client`
- Type:  `feature`
- Detail:

## TODO
1. [ ] 메인, 로그인 css 완성하기
2. [ ] 정보수정 페이지 코드 작성하기
3. [ ] 로그아웃 코드 작성하기

## Estimated time
> Pick one

`1d`

## Labels
* Estimated time: `E: 1d`
* Group : `client`
* Sprint: `Sprint__NUMBER__2`
* Urgency: `Middle`
