### ISSUE TITLE
[Task] 3/31 클라이언트 -2

### ISSUE THREAD

**Issue by mh11kim** [codestates/torys-journey#31]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail:

## TODO
1. [ ] 북마크 관리 코드 작성
2. [ ] 사진 업로드 모달창 코드 작성
3. [ ] 레스토랑 리스트, 레스토랑 상세 css

## Estimated time
> Pick one

`3h`

## Labels
* Estimated time: `E: 3h`
* Group : `client`
* Sprint: `Sprint__NUMBER__3`
* Urgency: `Middle`
