### ISSUE TITLE
[Task] 4/4 클라이언트-1

### ISSUE THREAD

**Issue by mh11kim** [codestates/torys-journey#43]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail:

## TODO
1. [ ] 케러셀 슬라이드 css수정
2. [ ] 케러셀 슬라이드 클릭시 넘어가는 코드 수정
3. [ ] 마이페이지 작성글관리 수정

## Estimated time
> Pick one

`3h`

## Labels
* Estimated time: `E: 3h`
* Group : `client`
* Sprint: `Sprint__NUMBER__4`
* Urgency: `Middle`
