### ISSUE TITLE
[Task] SR기획 4일차

### ISSUE THREAD

**Issue by mh11kim** [codestates/torys-journey#5]
## ISSUE
- Group: `client`, `server`
- Type: `bug`, `feature`, `delete`
- Detail: 부족한 부분 공부 하기

## TODO
1. [x] 타입스크립트 공부 하기
2. [x] css 공부 하기
3. [x] https로 배포 하기
4. [x] 클라이언트 배포 공부 

## Estimated time
> Pick one

`1d`

## Labels
* Estimated time: `E: 1d`
* Group : `client`, `server`
* Sprint: `Sprint__NUMBER__1`
* Urgency:  `Low`
